Exploratory analysis of NASDAQ data
blackswan-quants/nasdaq_causal-analysis_lstm pull request #13
Opened 2024-10-31 19:04 UTC by edoardomocchi

uploaded df on pickle file.
anlysis and plot on jupnotebook file called task1.
checkdata nel folder log.

2024-11-03 16:22 UTC, giutala requested changes
- do not name the file task1, name it after what it does 
- use helpermodules to pickle and clean the data: delete checkdata and make a main where we use the helpermodules 
- add conclusions to each thing you do on the notebook (check riccardo polo's notebook on clustering project) 
- why is the cointegration p value 1? make sure it is correct

2024-11-04 22:24 UTC, giutala requested changes
frequency and months, update

2024-11-04 22:24 UTC, giutala commented on main.py
> +df_nasdaq = IndexData_Retrieval(filename='nasdaq_dataframe', link='https://en.wikipedia.org/wiki/Nasdaq-100',months=2, frequency='1min') # Edoardo months and frequency?
frequency daily, months three years

2024-11-13 17:47 UTC, giutala requested changes
- do not push .gitmodules 
- make sure helpermodules is the latest version by running git submodule update --remote on the terminal

2024-11-17 10:22 UTC, ErTucano approved these changes

2024-11-26 20:11 UTC, closed without merging